### PR TITLE
:fire: Remove bower

### PR DESCRIPTION
**Pull request by notFloran**
#### Description

Remove bower and user npm

#### Resume

* Bug fix: no
* New feature: no
* Fixed tickets: #96

### CODE REVIEW

**Comment by notFloran** [comment]
@martin-damien @nclsHart Can you test this first version ?

Possible bug(s):

* "settings" link not working

**Comment by nclsHart** [comment]
@notFloran I confirm that the settings link is not working. 

The logo link seems to do crapy things too.

Tooltips are broken (last update, author and votes).

Everythings else seems to be working. Good job!

**Comment by notFloran** [comment]
@nclsHart thanks, I will fix that

**Comment by notFloran** [comment]
Some bugs came from angular 1.6, I downgrade to 1.5.

Tooltips were broken because I forgot to load sass files.

It's ok for review

**Review by nclsHart — APPROVED** [review]

**Pull request merged**
