### PR TITLE
New theme

### PR DESCRIPTION
**Pull request by nclsHart**
screenshot

todo : 
- [x] : update screenshot
- [x] : edit logo with new colors

@notFloran @martin-damien Comments are welcome ;).

### CODE REVIEW

**Comment by nclsHart** [comment]
@notFloran @martin-damien Ready for review.

**Comment by notFloran** [comment]
👍

**Comment by ghost** [comment]
Settings is not as visible as it should be. Can't you use a lighter color?

**Comment by nclsHart** [comment]
@martin-damien IMO no problem in live version. Could you try it in live ?

**Comment by ghost** [comment]
Just tryed and the color is "correct" (I still prefer it lighter but it do the job).
On the other hand, the number of +1 and -1 are really small to me. And It is not as easy to read than on the older version.

**Comment by nclsHart** [comment]
@martin-damien done.

**Comment by ghost** [comment]
Much better like this

**Pull request merged**
