### PR TITLE
Show numbers of merge requests in favicon

### LINKED ISSUE #2: Add a numbered favicon
It would be useful to add a favicon with the number of pending request displayed:
- `[0]`: Displays a green icon?
- `[1;9]`: Displays `1`, `2`, `3`, `4`, `5`, `6`, `7`, `8`, `9`
- `[10;19]`: Displays `10+`
- `[20;49]`: Displays `20+`
- `[50;99]`: Displays `50+`
- `[100;+∞[`: Displays `∞`

### PR DESCRIPTION
**Pull request by notFloran**
Show a favicon with the number of merge requests.

Fix #2 

Example : 
capture d ecran 2015-12-08 a 21 05 42

capture d ecran 2015-12-08 a 21 03 22

### CODE REVIEW

**Comment by ghost** [comment]
I like it, but I'm not sure we have the right to use this icon :p

**Comment by notFloran** [comment]
@martin-damien @nclsHart Where we can find "open source" favicon ?

**Comment by notFloran** [comment]
capture d ecran 2015-12-09 a 20 24 22

**Comment by nclsHart** [comment]
If you are searching a super simple flat icon, you can have a look to these sites : 
- https://thenounproject.com (mostly CC BY 3.0)
- http://www.flaticon.com (mostly CC BY 3.0)
- https://github.com/google/material-design-icons (CC BY 4.0)

**Comment by ghost** [comment]
I will try to do a vectorial logo for the project (we will talk about it at work).

**Comment by notFloran** [comment]
That would be great!

**Pull request merged**
