### PR TITLE
Power move !

### LINKED ISSUE #38: Implement GitLab oauth to avoid one install per user

### PR DESCRIPTION
**Pull request by notFloran**
Our current workflow is the following : 
- One install per user with `npm run serve`or hosted with nginx/apache/etc. See #38 and #32 

We can't host a version of MergeRequestCI for all users because the api url and private token of the user is injected in the js during the build.

My idea is : 
- no local config use during the build
- on first use of the UI, the user must set his api url, private token and others configurations on a form then data are stored in local storage

With this workflow : 
- we can host a single MergeRequestsCI for all team members
- Set a demo of the project to use with gitlab.com or other gitlab instance
- release the project as a single archive with html/js/css, no need for a build

We can event host it directly on Github/GitLab pages for our use and as demo.

Fixes #38 #32

Demo : https://hexanet.gitlab.io/MergeRequestsCI

Screenshots : 
capture d ecran 2016-04-20 a 21 58 42

### CODE REVIEW

**Comment by ghost** [comment]
Why hard coding refresh rate? I think that users should be able to set it up.

**Comment by notFloran** [comment]
It's a big WIP, I stil have lot of work.

But the refresh rate will be configurable by the user.

Le mardi 19 avril 2016, Martin Damien notifications@github.com a écrit :

> Why hard coding refresh rate? I think that users should be able to set it
> up.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Hexanet/MergeRequestsCI/pull/60#issuecomment-212102100

## 

Floran Brutel
PHP DevOps
_f.brutel@hexanet.fr f.brutel@hexanet.fr_

##

**Comment by notFloran** [comment]
@martin-damien I updated the PR description with more informations. cc @nclsHart

**Comment by ghost** [comment]
Now I'm ok with this!

**Comment by notFloran** [comment]
I almost finish the PR : so no more promise hell (special @nclsHart), a watchable login form (screenshot in the description) and error handling.

I think you can test this version and for warriors even review my PR.

I adds a todo to the PR description with the last things to finish.

**Comment by notFloran** [comment]
First working version here : https://hexanet.gitlab.io/MergeRequestsCI

ping @nclsHart @martin-damien

**Pull request merged**
